### ISSUE TITLE
[FP] Remote deployment

### ISSUE THREAD

**Issue by jmatsu** [jmatsu/splitter#25]
Allow to configure the remote service in the config and use it. Plugin-like mechanism is also fine.

**Comment by jmatsu** [comment]
```yaml
services:
  internal:
    endpoint: ...
    source_file: request_body
    # or
    source_file: params.file
    auth_header:
      name: Authorization
      value: Bearer %s
    # or
    auth_form_param:
      name: token
      value: %s
    # or
    auth_query:
      name: token
      value: %s
    default:
      headers:
        UPLOAD-AUTHOR: jmatsu
      query:
        filter: no
      form_params:
        message: hello
```

`splitter service --name internal --source-path ... --access-token ... --query x=y --header Accept=application/json`

this style also can achieve the goal, probably.
